shellcheck fixes

diff --git a/bin/nodenv-alias b/bin/nodenv-alias
--- a/bin/nodenv-alias
+++ b/bin/nodenv-alias
@@ -12,7 +12,7 @@
 
 shopt -s nullglob
 
-cd "$NODENV_ROOT/versions"
+cd "$NODENV_ROOT/versions" || exit
 
 resolve_link() {
   $(type -p greadlink readlink | head -1) "$1"
@@ -21,7 +21,7 @@ resolve_link() {
 list() {
   local exit=1
   local dir
-  for dir in $(echo_lines *); do
+  for dir in $(echo_lines ./*); do
     if [ -L "$dir" ]; then
       echo "$dir => $(resolve_link "$dir")"
       exit=0
@@ -33,9 +33,9 @@ list() {
 cleanup_invalid() {
   local version
   for version in *; do
-    if [ -L $version -a ! -e "$(resolve_link $version)" ]; then
-      echo "Removing invalid link from $version to $(resolve_link $version)"
-      rm $version
+    if [ -L "$version" ] && [ ! -e "$(resolve_link "$version")" ]; then
+      echo "Removing invalid link from $version to $(resolve_link "$version")"
+      rm "$version"
     fi
   done
 }
@@ -59,12 +59,14 @@ sort_semver() {
 }
 
 auto_for_point() {
-  local highest="$(echo_lines_without_symlinks $1* | sort_semver | tail -1)"
+  local highest
+  highest="$(echo_lines_without_symlinks "$1"* | sort_semver | tail -1)"
   echo "$highest"
 }
 
 auto_symlink_point() {
-  local auto="$(auto_for_point $1)"
+  local auto
+  auto="$(auto_for_point "$1")"
   if [ -z "$auto" ]; then
     echo "Couldn't find any versions for $1" >&2
   else
@@ -99,7 +101,7 @@ case "$#" in
       case "$2" in -*) nodenv-help --usage alias ;; esac
       nodenv-alias "$2" "$1" ;;
     esac
-    if [ -e "$1" -a ! -L "$1" ]; then
+    if [ -e "$1" ] && [ ! -L "$1" ]; then
       echo "Not clobbering $1" >&2
       exit 1
     elif [ --remove = "$2" ]; then
@@ -133,7 +135,7 @@ case "$#" in
       --auto | --all)
         cleanup_invalid
         for point in $(point_releases); do
-          auto_symlink_point $point
+          auto_symlink_point "$point"
         done
         ;;
       -*)
